### ISSUE TITLE
Where to get the used ref files?

### ISSUE THREAD

**Issue by oguzeroglu** [johnlees/23andme-impute#2]
Hello,

I'm confused about where to download the hardcoded ref files such as: ALL_1000G_phase1integrated_v3_chr1_impute.legend.gz.gz

Is there a public access URL from where I can download those?

Thanks!

**Comment by johnlees** [comment]
There's some more information listed here:
http://www.johnlees.me/blog/2014/03/18/impute-your-whole-genome-from-23andme-data/

But this is all a bit old. You might consider alternatives e.g. https://www.impute.me/
